# Generated by Django 4.2.11 on 2024-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=200, null=True, verbose_name='Grade '),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Last name '),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(max_length=200, null=True, verbose_name='Middle name '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classtype',
            field=models.CharField(max_length=200, null=True, verbose_name='Class type '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='First name '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Last name '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roomnumber',
            field=models.CharField(max_length=200, null=True, verbose_name='Room Number '),
        ),
    ]
